### PR TITLE
minor markdown fix

### PR DESCRIPTION
**Pull request by billybonks**
This is awesome :).

Not sure why it wasn't rendering properly. probably some strange char instead of space.

### CODE REVIEW

**Comment by mansona** [comment]
@billybonks that seems to have done it! 

I have no idea where that character came from 🤔

**Comment by billybonks** [comment]
lol ye 👍

**Comment by billybonks** [comment]
https://github.com/stonecircle/broccoli-static-site-json/commit/c475d8b88b9dcf6f7e3367be4f39336146fec1f9

editor?

**Comment by mansona** [comment]
I'm in Atom on Mac and I've not had any issues with this sort of stuff before 🤔 I've been doing a **lot** of markdown recently.

I had another issue where it seems like Atom is trying to replace that character for the bad one automatically when I save. 

I'll have to dig into it at some point

**Pull request merged**
